version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for live reload (exclude node_modules)
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      # Use named volume for node_modules to avoid conflicts
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=ecommerce
      - SERVER_PORT=8080
    volumes:
      # Mount source code for live reload
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      # Use named volume for Maven dependencies to avoid conflicts
      - backend_maven_deps:/app/target

volumes:
  frontend_node_modules:
  backend_maven_deps: