version: '3.8'

services:
  ecommerce-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://tanyanho123:S5o1ldeaWAau18eX@cluster0.5ixikmy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      SPRING_DATA_MONGODB_DATABASE: ecommerce
      SERVER_PORT: 8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
