# Use Maven with JDK 17 as the base image
FROM maven:3.9.6-eclipse-temurin-21 AS backend-build

# Set working directory
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the rest of the backend code
COPY src ./src

# Build the application
RUN mvn package -DskipTests

# Expose port 8080
EXPOSE 8080

# Run the Spring Boot app
CMD ["java", "-jar", "target/ecommerce-0.0.1-SNAPSHOT.jar"]